### ISSUE TITLE
ACSI2STM Compact  help with setting up card

### ISSUE THREAD

**Issue by gdjores** [longissor/ACSI2STM-Quick-Start-Guide#1]
I have just received the circuits for the above,i need to program the STm , how do i power the board? and how do i connect to the windows laptop.i have a uart to usb connector.I have set up a an stm for the onstep project so i have a basic idea.
Thanks Gary jores

**Comment by longissor** [comment]
Hello.

Did you buy the card from me? If yes, then the card is ready to be used on your Atari ST
You power my card using a USB-C cable and any phone charger.

If you built your card or bought it from someone else, then you need to follow the link https://github.com/retro16/acsi2stm

can you send me a photo of your card?
If it is from me, it should look like this
![image](https://github.com/longissor/ACSI2STM-Quick-Start-Guide/assets/139055177/f04fab7e-7a16-4517-aac0-c3b5313e4240)


Best regards,
Cyril

**Comment by gdjores** [comment]
hello,I ordered the board from china , its the same as yours but it needs setting up.GJ

    On Wednesday, 20 December 2023 at 11:04:40 CET, longissor ***@***.***> wrote:  
 
 


Hello.

Did you buy the card from me? If yes, then the card is ready to be used on your Atari ST
You power my card using a USB-C cable and any phone charger.

If you built your card or bought it from someone else, then you need to follow the link https://github.com/retro16/acsi2stm

can you send me a photo of your card?
If it is from me, it should look like this
image.png (view on web)

Best regards,
Cyril

**Comment by longissor** [comment]
Hello,

In this case, please refer to the official ACSI2STM GitHub. Specifically here: https://github.com/retro16/acsi2stm/blob/stable/doc/flashing.md


My GitHub repository does not cover flashing the board since I sell them already flashed and ready to use.

Best regards
Cyril

**Comment by gdjores** [comment]
Hi again,This location gives lots of info but it does not cover as far as i can see how to connect to . program the card and how to power it for programming.I am thinking if i use arduino i would need an usb to uart connection?Thanks GJ








    On Wednesday, 20 December 2023 at 11:04:40 CET, longissor ***@***.***> wrote:  
 
 


Hello.

Did you buy the card from me? If yes, then the card is ready to be used on your Atari ST
You power my card using a USB-C cable and any phone charger.

If you built your card or bought it from someone else, then you need to follow the link https://github.com/retro16/acsi2stm

can you send me a photo of your card?
If it is from me, it should look like this
image.png (view on web)

Best regards,
Cyril

**Comment by gdjores** [comment]
ok thanks

    On Wednesday, 20 December 2023 at 11:13:11 CET, longissor ***@***.***> wrote:  
 
 


Hello,

In this case, please refer to the official ACSI2STM GitHub. Specifically here: https://github.com/retro16/acsi2stm/blob/stable/doc/flashing.md

My GitHub repository does not cover flashing the board since I sell them already flashed and ready to use.

Best regards
Cyril

**Comment by longissor** [comment]
If you got the compact version made for you, that means you have the file "quick_start.md" that explain how to connect your USB adapter.

**If you don't have that very specific model of adapter, plug as following:

* Make sure your adapter works with 3.3V signals. 5V signals may damage the
  STM32.
* Plug GND to the GND pin of your adapter.
* Plug TX to RX of your adapter, RX to TX of your adapter.
* Enable (short) the FLASH jumper or put 5V on the 5V pin of the UART header.
* Put a 3.3V source on any of the 3.3V pins of the UART header.
* As soon as power is applied, the STM32 is ready to receive its firmware.**

My USB adapter used 3.3V. I follow the steps above.

I use the command-line method. No Arduino. Just these steps:

**### Flashing using the stm32flash command-line

You need the `stm32flash` command-line tool available on the
[Arduino_STM32](https://github.com/rogerclarkmelbourne/Arduino_STM32/tree/master/tools)
repository, in the tools subdirectory.

Sample stm32flash command-line:

    stm32flash -w acsi2stm.ino.bin COM3

You need to adapt the command-line for your setup: COM3 should point at
the serial port connected to the STM32**

**Comment by gdjores** [comment]
Thanks much appreciated!!!

    On Wednesday, 20 December 2023 at 11:23:47 CET, longissor ***@***.***> wrote:  
 
 


If you got the compact version made for you, that means you have the file "quick_start.md" that explain how to connect your USB adapter.

**If you don't have that very specific model of adapter, plug as following:
   
   - Make sure your adapter works with 3.3V signals. 5V signals may damage the   
STM32.
   - Plug GND to the GND pin of your adapter.
   - Plug TX to RX of your adapter, RX to TX of your adapter.
   - Enable (short) the FLASH jumper or put 5V on the 5V pin of the UART header.
   - Put a 3.3V source on any of the 3.3V pins of the UART header.
   - As soon as power is applied, the STM32 is ready to receive its firmware.**

My USB adapter used 3.3V. I follow the steps above.

I use the command-line method. No Arduino. Just these steps:

**### Flashing using the stm32flash command-line

You need the stm32flash command-line tool available on the
Arduino_STM32
repository, in the tools subdirectory.

Sample stm32flash command-line:
stm32flash -w acsi2stm.ino.bin COM3

You need to adapt the command-line for your setup: COM3 should point at
the serial port connected to the STM32**
